export const REGIONES_CHILE = [
  "Región Metropolitana de Santiago",
];

export const COMUNAS_RM = [
  "Cerrillos",
  "Cerro Navia",
  "Conchalí",
  "El Bosque",
  "Estación Central",
  "Huechuraba",
  "Independencia",
  "La Cisterna",
  "La Florida",
  "La Granja",
  "La Pintana",
  "La Reina",
  "Las Condes",
  "Lo Barnechea",
  "Lo Espejo",
  "Lo Prado",
  "Macul",
  "Maipú",
  "Ñuñoa",
  "Pedro Aguirre Cerda",
  "Peñalolén",
  "Providencia",
  "Pudahuel",
  "Quilicura",
  "Quinta Normal",
  "Recoleta",
  "Renca",
  "San Joaquín",
  "San Miguel",
  "San Ramón",
  "Santiago",
  "Vitacura",
  "Colina",
  "Lampa",
  "Tiltil",
  "Pirque",
  "Puente Alto",
  "San José de Maipo",
  "Buin",
  "Calera de Tango",
  "Paine",
  "San Bernardo",
  "Alhué",
  "Curacaví",
  "María Pinto",
  "Melipilla",
  "San Pedro",
  "El Monte",
  "Isla de Maipo",
  "Padre Hurtado",
  "Peñaflor",
  "Talagante",
];