// 1. Creamos el objeto en el formato que el frontend espera
const UBICACIONES = {
  "Región Metropolitana": [
    "Cerrillos",
    "Cerro Navia",
    "Conchalí",
    "El Bosque",
    "Estación Central",
    "Huechuraba",
    "Independencia",
    "La Cisterna",
    "La Florida",
    "La Granja",
    "La Pintana",
    "La Reina",
    "Las Condes",
    "Lo Barnechea",
    "Lo Espejo",
    "Lo Prado",
    "Macul",
    "Maipú",
    "Ñuñoa",
    "Pedro Aguirre Cerda",
    "Peñalolén",
    "Providencia",
    "Pudahuel",
    "Quilicura",
    "Quinta Normal",
    "Recoleta",
    "Renca",
    "San Joaquín",
    "San Miguel",
    "San Ramón",
    "Santiago",
    "Vitacura",
    "Colina",
    "Lampa",
    "Tiltil",
    "Pirque",
    "Puente Alto",
    "San José de Maipo",
    "Buin",
    "Calera de Tango",
    "Paine",
    "San Bernardo",
    "Alhué",
    "Curacaví",
    "María Pinto",
    "Melipilla",
    "San Pedro",
    "El Monte",
    "Isla de Maipo",
    "Padre Hurtado",
    "Peñaflor",
    "Talagante",
  ]
  // Si agregas más regiones, hazlo aquí.
  // "Región de Valparaíso": ["Viña del Mar", "Valparaíso", ...],
};

// 2. Exportamos ese objeto como la exportación "por defecto"
export default UBICACIONES;